config:
  MD013: false
  MD025: false
  MD033: false
  MD024: { siblings_only: true }
  MD026: false
  MD036: false
  MD041: false
  MD040: true
  MD004: { style: "dash" }
  MD060: false

globs:
  - "docs/book/src/**/*.md"
  - "README.md"
  - "CONTRIBUTING.md"

ignores:
  - "docs/tasks/**"
  - "docs/plans/**"
  - "docs/design/**"
