use anyhow::{Context, Result};
use std::path::Path;

use super::types::find_bobbin_root;
use super::state::{HookState, ChunkFrequency, load_hook_state};
use super::{HotTopicsArgs, OutputConfig};

/// Generate `.bobbin/hot-topics.md` from injection frequency data.
pub(super) fn generate_hot_topics(state: &HookState, output_path: &Path) -> Result<()> {
    use std::fmt::Write;

    let mut md = String::new();
    writeln!(md, "# Hot Topics (auto-generated by bobbin)").unwrap();
    writeln!(md).unwrap();

    let timestamp = if state.last_injection_time.is_empty() {
        "never".to_string()
    } else {
        // Truncate to minute precision for readability
        state
            .last_injection_time
            .get(..16)
            .unwrap_or(&state.last_injection_time)
            .replace('T', " ")
            + " UTC"
    };
    writeln!(md, "Last updated: {}", timestamp).unwrap();
    writeln!(
        md,
        "Based on {} context injections.",
        state.injection_count
    )
    .unwrap();
    writeln!(md).unwrap();

    // Frequently referenced chunks, sorted by count descending
    let mut chunks: Vec<(&String, &ChunkFrequency)> = state.chunk_frequencies.iter().collect();
    chunks.sort_by(|a, b| b.1.count.cmp(&a.1.count));
    chunks.truncate(20);

    writeln!(md, "## Frequently Referenced Code").unwrap();
    writeln!(md).unwrap();
    if chunks.is_empty() {
        writeln!(md, "No injection data yet.").unwrap();
    } else {
        writeln!(md, "| Rank | File | Symbol | Injections |").unwrap();
        writeln!(md, "|------|------|--------|------------|").unwrap();
        for (i, (_key, freq)) in chunks.iter().enumerate() {
            let symbol = freq.name.as_deref().unwrap_or("-");
            writeln!(
                md,
                "| {} | {} | {} | {} |",
                i + 1,
                freq.file,
                symbol,
                freq.count
            )
            .unwrap();
        }
    }
    writeln!(md).unwrap();

    // Most referenced files, sorted by count descending
    let mut files: Vec<(&String, &u64)> = state.file_frequencies.iter().collect();
    files.sort_by(|a, b| b.1.cmp(a.1));
    files.truncate(10);

    writeln!(md, "## Most Referenced Files").unwrap();
    writeln!(md).unwrap();
    if files.is_empty() {
        writeln!(md, "No injection data yet.").unwrap();
    } else {
        writeln!(md, "| File | Total Injections |").unwrap();
        writeln!(md, "|------|-----------------|").unwrap();
        for (file, count) in &files {
            writeln!(md, "| {} | {} |", file, count).unwrap();
        }
    }
    writeln!(md).unwrap();

    writeln!(md, "## Notes").unwrap();
    writeln!(md).unwrap();
    writeln!(
        md,
        "- Chunks appearing here are candidates for pinning in CLAUDE.md or session context."
    )
    .unwrap();
    writeln!(
        md,
        "- Regenerated every 10 injections. Run `bobbin hook hot-topics` to force refresh."
    )
    .unwrap();

    std::fs::write(output_path, md).context("Failed to write hot-topics.md")?;
    Ok(())
}

pub(super) async fn run_hot_topics(args: HotTopicsArgs, _output: OutputConfig) -> Result<()> {
    let cwd = if args.path == Path::new(".") {
        std::env::current_dir().context("Failed to get cwd")?
    } else {
        args.path.clone()
    };

    let repo_root = find_bobbin_root(&cwd).context("Bobbin not initialized in this directory")?;
    let state = load_hook_state(&repo_root);

    if !args.force && state.injection_count == 0 {
        println!("No injection data yet. Run with --force to generate anyway.");
        return Ok(());
    }

    let output_path = repo_root.join(".bobbin").join("hot-topics.md");
    generate_hot_topics(&state, &output_path)?;
    println!(
        "Generated {} ({} injections, {} chunks tracked)",
        output_path.display(),
        state.injection_count,
        state.chunk_frequencies.len()
    );
    Ok(())
}
